import json
from typing import Optional
from fastapi import APIRouter, Depends
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from app.dependencies import get_current_user
from app.auth.jwt_handler import UserContext
from app.agent.graph import run_agent

router = APIRouter(prefix="/api/chat", tags=["chat"])

class ChatRequest(BaseModel):
    message: str
    conversation_id: Optional[str] = "default"

@router.post("")
async def chat_endpoint(request: ChatRequest, user: UserContext = Depends(get_current_user)):
    """
    Main entry point for the Agentic RAG chat.
    Uses Server-Sent Events (SSE) to stream back the agent's progress, tool calls, and final answer.
    """
    async def event_generator():
        try:
            tokens_streamed = False
            # Isolate conversation memory by user_id to prevent memory leakage between users/roles
            thread_id = f"{user.user_id}_{request.conversation_id}"
            async for event in run_agent(request.message, user.user_id, user.role, thread_id):
                kind = event["event"]
                
                # We can stream tokens as they are generated by the LLM
                if kind == "on_chat_model_stream":
                    node_name = event.get("metadata", {}).get("langgraph_node", "")
                    # Only stream tokens from the final answer nodes, not internal reasoning/SQL generation!
                    if node_name in ["llm_generation", "direct_response"]:
                        content = event["data"]["chunk"].content
                        if content:
                            tokens_streamed = True
                            yield f"data: {json.dumps({'type': 'token', 'content': content})}\n\n"
                        
                # Send progress updates to the UI so the user knows it's thinking!
                elif kind == "on_chain_start":
                    node_name = event.get("name", "")
                    if node_name == "database_query_node":
                        yield f"data: {json.dumps({'type': 'token', 'content': '*(⏳ Accessing Secure Database...)*\\n\\n'})}\n\n"
                    elif node_name == "hybrid_retrieval_node":
                        yield f"data: {json.dumps({'type': 'token', 'content': '*(⏳ Searching Documents...)*\\n\\n'})}\n\n"
                
                # If we bypassed the LLM, manually stream the hardcoded answer at the end of the node
                elif kind == "on_chain_end":
                    node_name = event.get("name", "")
                    if node_name in ["llm_generation", "direct_response"]:
                        if not tokens_streamed:
                            output = event.get("data", {}).get("output", {})
                            if isinstance(output, dict) and "answer" in output:
                                yield f"data: {json.dumps({'type': 'token', 'content': output['answer']})}\n\n"
                    # And finally, the complete state updates from the graph nodes
                    elif node_name == "agent":
                        final_state = event["data"]["output"]
                        yield f"data: {json.dumps({'type': 'final_state', 'state': final_state})}\n\n"
                    
        except Exception as e:
            yield f"data: {json.dumps({'type': 'error', 'message': str(e)})}\n\n"
            
    return StreamingResponse(event_generator(), media_type="text/event-stream")
